import pandas as pd

rename_columns = {
    'DDoS-ALL': 'DDoS-ALL',
    'Phishing-ALL': 'Phishing-ALL',
    'Ransomware-ALL': 'Ransomware-ALL',
    'Password Attack-ALL': 'Password Attack-ALL',
    'Account Hijacking-ALL': 'Account Hijacking-ALL',
    'Trojan-ALL': 'Trojan-ALL',
    'Vulnerability-ALL': 'Vulnerability-ALL',
    'Zero-day-ALL': 'Zero-day-ALL',
    'Advanced persistent threat-ALL': 'Advanced persistent threat-ALL',
    'Malware-ALL': 'Malware-ALL',
    'Disinformation/Misinformation-ALL': 'Disinformation/Misinformation-ALL',
    'Targeted Attack-ALL': 'Targeted Attack-ALL',
    'Brute Force Attack-ALL': 'Brute Force Attack-ALL',
    'Backdoor-ALL': 'Backdoor-ALL',
    'Botnet-ALL': 'Botnet-ALL',
    'Cryptojacking-ALL': 'Cryptojacking-ALL',

    # Mentions -> Papers
    'Mentions-MITM': 'MITM',
    'Mentions-DNS Spoofing': 'DNS_Spoofing',
    'Mentions-Dropper': 'Dropper',
    'Mentions-Insider Threat': 'Insider_Threat',
    'Mentions-Adversarial Attack': 'Adversarial_Attack',
    'Mentions-Data Poisoning': 'Data_Poisoning',
    'Mentions-Deepfake': 'Deepfake',
    'Mentions-Supply Chain': 'Supply_Chain',
    'Mentions-IoT Device Attack': 'IoT_Device_Attack',
    'Mentions-Session Hijacking': 'Session_Hijacking',

    # 공격/위협 ALL 
    'DDoS-ALL': 'DDoS',
    'Phishing-ALL': 'Phishing',
    'Ransomware-ALL': 'Ransomware',
    'Password Attack-ALL': 'Password_Attack',
    'Account Hijacking-ALL': 'Account_Hijacking',
    'Trojan-ALL': 'Trojan',
    'Vulnerability-ALL': 'Vulnerability',
    'Zero-day-ALL': 'Zero_day',
    'Advanced persistent threat-ALL': 'Advanced_Persistent_Threat',
    'Malware-ALL': 'Malware',
    'Disinformation/Misinformation-ALL': 'Disinformation/Misinformation',
    'Targeted Attack-ALL': 'Targeted_Attack',
    'Brute Force Attack-ALL': 'Brute_Force_Attack',
    'Backdoor-ALL': 'Backdoor',
    'Botnet-ALL': 'Botnet',
    'Cryptojacking-ALL': 'Cryptojacking',
    
    # 새로운 항목
    'War_Conflict_All': 'War_Conflict_All',
    'Holidays': 'Holidays',
    
    # Solution_..._Mentions -> Solution_... (ML/DL, Bayesian Network, NLP/LLM 특이사항 반영)
    'Solution_BLOCKCHAIN_Mentions': 'Solution_BLOCKCHAIN',
    'Solution_ACCESS CONTROL_Mentions': 'Solution_ACCESS_CONTROL',
    'Solution_ENCRYPTION_Mentions': 'Solution_ENCRYPTION',
    'Solution_SUPPLY CHAIN RISK MANAGEMENT_Mentions': 'Solution_SUPPLY_CHAIN_RISK_MANAGEMENT',
    'Solution_IDENTITY MANAGEMENT_Mentions': 'Solution_IDENTITY_MANAGEMENT',
    'Solution_MACHINE LEARNING_Mentions': 'Solution_ML/DL', # 특이사항
    'Solution_ANOMALY DETECTION_Mentions': 'Solution_ANOMALY_DETECTION',
    'Solution_CRYPTOGRAPHY_Mentions': 'Solution_CRYPTOGRAPHY',
    'Solution_PENETRATION TESTING_Mentions': 'Solution_PENETRATION_TESTING',
    'Solution_IDS/IPS_Mentions': 'Solution_IDS/IPS',
    'Solution_STATIC ANALYSIS_Mentions': 'Solution_STATIC_ANALYSIS',
    'Solution_DYNAMIC ANALYSIS_Mentions': 'Solution_DYNAMIC_ANALYSIS',
    'Solution_MULTI FACTOR AUTHENTICATION_Mentions': 'Solution_MULTI_FACTOR_AUTHENTICATION',
    'Solution_LEAST PRIVILEGE_Mentions': 'Solution_LEAST_PRIVILEGE',
    'Solution_SESSION MANAGEMENT_Mentions': 'Solution_SESSION_MANAGEMENT',
    'Solution_CAPTCHA_Mentions': 'Solution_CAPTCHA',
    'Solution_BLACKLISTING_Mentions': 'Solution_BLACKLISTING',
    'Solution_RATE LIMITING_Mentions': 'Solution_RATE_LIMITING',
    'Solution_GRAPHICAL MODEL_Mentions': 'Solution_GRAPHICAL_MODEL',
    'Solution_HONEYPOT_Mentions': 'Solution_HONEYPOT',
    'Solution_SOFTWARE DEFINED NETWORK_Mentions': 'Solution_SOFTWARE_DEFINED_NETWORK',
    'Solution_GAME THEORY_Mentions': 'Solution_GAME_THEORY',
    'Solution_TRAFFIC SHAPING_Mentions': 'Solution_TRAFFIC_SHAPING',
    'Solution_PACKET FILTERING_Mentions': 'Solution_PACKET_FILTERING',
    'Solution_BLACKHOLING_Mentions': 'Solution_BLACKHOLING',
    'Solution_RANK CORRELATION_Mentions': 'Solution_RANK_CORRELATION',
    'Solution_STRONG AUTHENTICATION_Mentions': 'Solution_STRONG_AUTHENTICATION',
    'Solution_SSL/TLS_Mentions': 'Solution_SSL/TLS',
    'Solution_HTTPS_Mentions': 'Solution_HTTPS',
    'Solution_CONTINUOUS AUTHENTICATION_Mentions': 'Solution_CONTINUOUS_AUTHENTICATION',
    'Solution_Identity-Based Encryption (IBE)_Mentions': 'Solution_IDENTITY_BASED_ENCRYPTION',
    'Solution_DATA SANITIZATION_Mentions': 'Solution_DATA_SANITIZATION',
    'Solution_OUTLIER DETECTION_Mentions': 'Solution_OUTLIER_DETECTION',
    'Solution_DATA PROVENANCE_Mentions': 'Solution_DATA_PROVENANCE',
    'Solution_ADVERSARIAL TRAINING_Mentions': 'Solution_ADVERSARIAL_TRAINING',
    'Solution_TRUSTWORTHY AI_Mentions': 'Solution_TRUSTWORTHY_AI',
    'Solution_Bayesian Network_Mentions': 'Solution_BAYESIAN_NETWORK', # 특이사항
    'Solution_BEHAVIOR BASED DETECTION_Mentions': 'Solution_BEHAVIOR_BASED_DETECTION',
    'Solution_FORMAL VERIFICATION_Mentions': 'Solution_FORMAL_VERIFICATION',
    'Solution_SPLIT MANUFACTURING_Mentions': 'Solution_SPLIT_MANUFACTURING',
    'Solution_VULNERABILITY MANAGEMENT_Mentions': 'Solution_VULNERABILITY_MANAGEMENT',
    'Solution_FILE INTEGRITY MONITORING_Mentions': 'Solution_FILE_INTEGRITY_MONITORING',
    'Solution_VPN_Mentions': 'Solution_VPN',
    'Solution_PRIVACY PRESERVING_Mentions': 'Solution_PRIVACY_PRESERVING',
    'Solution_SECURE BOOT_Mentions': 'Solution_SECURE_BOOT',
    'Solution_MERKLE SIGNATURE_Mentions': 'Solution_MERKLE_SIGNATURE',
    'Solution_LIVENESS DETECTION_Mentions': 'Solution_LIVENESS_DETECTION',
    'Solution_3D FACE RECONSTRUCTION_Mentions': 'Solution_3D_FACE_RECONSTRUCTION',
    'Solution_BIOMETRICS_Mentions': 'Solution_BIOMETRICS',
    'Solution_DIGITAL WATERMARK_Mentions': 'Solution_DIGITAL_WATERMARK',
    'Solution_APPLICATION WHITELISTING_Mentions': 'Solution_APPLICATION_WHITELISTING',
    'Solution_DATA BACKUPS_Mentions': 'Solution_DATA_BACKUPS',
    'Solution_HIDDEN MARKOV MODEL_Mentions': 'Solution_HIDDEN_MARKOV_MODEL',
    'Solution_PATCH MANAGEMENT_Mentions': 'Solution_PATCH_MANAGEMENT',
    'Solution_DATA AUGMENTATION_Mentions': 'Solution_DATA_AUGMENTATION',
    'Solution_DIMENSIONALITY REDUCTION_Mentions': 'Solution_DIMENSIONALITY_REDUCTION',
    'Solution_DEFENSIVE DISTILLATION_Mentions': 'Solution_DEFENSIVE_DISTILLATION',
    'Solution_RRAM_Mentions': 'Solution_RRAM',
    'Solution_SPATIAL SMOOTHING_Mentions': 'Solution_SPATIAL_SMOOTHING',
    'Solution_NOISE INJECTION_Mentions': 'Solution_NOISE_INJECTION',
    'Solution_TAINT ANALYSIS_Mentions': 'Solution_TAINT_ANALYSIS',
    'Solution_NETWORK SEGMENTATION_Mentions': 'Solution_NETWORK_SEGMENTATION',
    'Solution_USER BEHAVIOR ANALYTICS_Mentions': 'Solution_USER_BEHAVIOR_ANALYTICS',
    'Solution_DECEPTION TECHNOLOGY_Mentions': 'Solution_DECEPTION_TECHNOLOGY',
    'Solution_RISK ASSESSMENT_Mentions': 'Solution_RISK_ASSESSMENT',
    'Solution_DYNAMIC RESOURCE MANAGEMENT_Mentions': 'Solution_DYNAMIC_RESOURCE_MANAGEMENT',
    'Solution_SANDBOXING_Mentions': 'Solution_SANDBOXING',
    'Solution_DARKNET MONITORING_Mentions': 'Solution_DARKNET_MONITORING',
    'Solution_VIRTUAL KEYBOARDS_Mentions': 'Solution_VIRTUAL_KEYBOARDS',
    'Solution_CODE SIGNING_Mentions': 'Solution_CODE_SIGNING',
    'Solution_PUBLIC KEY INFRASTRUCTURE_Mentions': 'Solution_PUBLIC_KEY_INFRASTRUCTURE',
    'Solution_MUTUAL AUTHENTICATION_Mentions': 'Solution_MUTUAL_AUTHENTICATION',
    'Solution_ONE TIME PASSWORD_Mentions': 'Solution_ONE_TIME_PASSWORD',
    'Solution_DYNAMIC BINARY INSTRUMENTATION_Mentions': 'Solution_DYNAMIC_BINARY_INSTRUMENTATION',
    'Solution_PASSWORD HASHING_Mentions': 'Solution_PASSWORD_HASHING',
    'Solution_DNSSEC_Mentions': 'Solution_DNSSEC',
    'Solution_CERTIFICATE PINNING_Mentions': 'Solution_CERTIFICATE_PINNING',
    'Solution_SECURE SIMPLE PAIRING_Mentions': 'Solution_SECURE_SIMPLE_PAIRING',
    'Solution_VULNERABILITY ASSESSMENT_Mentions': 'Solution_VULNERABILITY_ASSESSMENT',
    'Solution_SIEM_Mentions': 'Solution_SIEM',
    'Solution_STANDARDIZED COMMUNICATION_Mentions': 'Solution_STANDARDIZED_COMMUNICATION',
    'Solution_Control Flow Integrity_Mentions': 'Solution_CONTROL_FLOW_INTEGRITY',
    'Solution_VULNERABILITY SCANNER_Mentions': 'Solution_VULNERABILITY_SCANNER',
    'Solution_PASSWORD STRENGTH METERS_Mentions': 'Solution_PASSWORD_STRENGTH_METERS',
    'Solution_PASSWORD MANAGEMENT_Mentions': 'Solution_PASSWORD_MANAGEMENT',
    'Solution_PASSWORD POLICY_Mentions': 'Solution_PASSWORD_POLICY',
    'Solution_GRAPHICAL AUTHENTICATION_Mentions': 'Solution_GRAPHICAL_AUTHENTICATION',
    'Solution_DATA LOSS PREVENTION_Mentions': 'Solution_DATA_LOSS_PREVENTION',
    'Solution_DATA LEAKAGE DETECTION/PREVENTION_Mentions': 'Solution_DATA_LEAKAGE_DETECTION/PREVENTION',
    'Solution_ACTIVITY MONITORING_Mentions': 'Solution_ACTIVITY_MONITORING',
    'Solution_MOVING TARGET DEFENSE_Mentions': 'Solution_MOVING_TARGET_DEFENSE',
    'Solution_KEYSTROKE DYNAMICS_Mentions': 'Solution_KEYSTROKE_DYNAMICS',
    'Solution_ATTACK TREE_Mentions': 'Solution_ATTACK_TREE',
    'Solution_DISTRIBUTED LEDGERS_Mentions': 'Solution_DISTRIBUTED_LEDGERS',
    'Solution_SOURCE IDENTIFICATION_Mentions': 'Solution_SOURCE_IDENTIFICATION',
    'Solution_IMAGE RECOGNITION_Mentions': 'Solution_IMAGE_RECOGNITION',
    'Solution_HYPERGAME_Mentions': 'Solution_HYPERGAME',
    
    # 마지막 추가 항목
    'Solution_NLP/LLM_Mentions': 'Solution_NLP/LLM' # 기존 리스트에는 없었으므로 빈 문자열로 처리 (또는 누락된 항목임을 표시)
}


df_graph = pd.read_csv('data/graph.csv').fillna('')
df_graph = df_graph.replace(rename_columns)
df_graph.to_csv('data/graph_new.csv', index=False)
# print(df_graph)